# Generated by Django 3.2.3 on 2021-05-29 04:07

import colorfield.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oftoday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('moods', models.CharField(choices=[('1', '행벅'), ('2', '꿀꿀'), ('3', '짜증'), ('4', '우울'), ('5', '평온'), ('6', '나도 날 몰라')], max_length=50)),
                ('content', models.TextField()),
                ('day', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Totd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('color', colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default='#FFFFFF', max_length=18)),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='fotd',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ootd',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
