# Generated by Django 3.2.3 on 2021-05-29 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oftoday', '0002_auto_20210529_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='totd',
            name='content',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='fotd',
            name='content',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='motd',
            name='content',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ootd',
            name='content',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=40)),
                ('introduction', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like_Ootd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ootd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_ootd', to='oftoday.ootd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_ootd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like_Fotd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_fotd', to='oftoday.fotd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_fotd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
