# Generated by Django 3.2.3 on 2021-05-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oftoday', '0003_auto_20210529_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='시작시간')),
                ('end_time', models.DateTimeField(verbose_name='마감시간')),
                ('title', models.CharField(max_length=50, verbose_name='이벤트 이름')),
                ('description', models.TextField(verbose_name='상세')),
            ],
            options={
                'verbose_name': '이벤트 데이터',
                'verbose_name_plural': '이벤트 데이터',
            },
        ),
    ]
