# Generated by Django 3.2.3 on 2021-05-29 15:40

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oftoday', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotd',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ootd',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='totd',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FDFBC7', '1'), ('#ECC5C7', '2'), ('#E29EAF', '3'), ('#A38FAB', '4'), ('#918DAB', '5'), ('#79849F', '6')], default='#FFFFFF', max_length=18),
        ),
    ]
